on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: curveSecp256k1
          code-coverage: true
          upload-logs: always
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: encryption_aes_cbc_sha512
          code-coverage: true
          upload-logs: always
